#!/bin/sh
appdir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export PATH="$appdir/usr/bin${PATH:+:$PATH}"
export LD_LIBRARY_PATH="$appdir/usr/lib:$appdir/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="$appdir/usr/plugins${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
export QML2_IMPORT_PATH="$appdir/usr/qml${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}"
export GST_PLUGIN_SYSTEM_PATH_1_0="$appdir/usr/lib/gstreamer-1.0"
export GST_PLUGIN_SCANNER="$appdir/usr/libexec/gstreamer-1.0/gst-plugin-scanner"
exec "$appdir/usr/bin/pptalk-desktop" "$@"
